HAPS_CONFPROSH: /path/to/confprosh
HAPS_DB_LOADING_TCL: /path/to/haps80_database_cfg.tcl
HAPS_PLATFORM: [CD-HAPS80, BJ-HAPS80, CD-HAPS100-05, CD-HAPS100-11]
UART_DEVICE: [/dev/ttyUSB0, /dev/ttyUSB1]
UART_LOG_PATH: /data/default_tmplog/
HAPS_RESET_TCL: /path/to/reset_release.tcl
HAPS_IMG_LOADING_TCL: /paht/to/load_ap.tcl
HAPS_HMF_TXT: /path/to/hmf.txt
SERVICE_PORT: 8000
CREATE_JOBS_MAX_NUM: 5
RECENT_JOBS_MAX_NUM: 10
TERMINAL: /ternminal/path/bin/terminator
CHROME_EXTENSION_ID: replace_with_chrome_extension_id
NATIVE_HOST_NAME: com.haps.job_console_host
