HAPS_CONFPROSH: /tools/synopsys/R-2020.12-SP1-1/bin/confprosh
HAPS_DB_LOADING_TCL: /home/e0007295/app_test/haps80_database_cfg.tcl
HAPS_PLATFORM: [CD-HAPS80, BJ-HAPS80, CD-HAPS100-05, CD-HAPS100-11]
UART_LOG_PATH: /data/default_tmplog/
HAPS_RESET_TCL: /home/e0007295/app_test/reset_release.tcl
HAPS_IMG_LOADING_TCL: /home/e0007295/bulk/load_ap.tcl
HAPS_HMF_TXT: /home/e0007295/app_test/hmf.txt
